# 가짜데이터 만들기

In [2]:
!pip install faker

Collecting faker
  Downloading Faker-26.0.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in c:\users\pooko\appdata\roaming\python\python312\site-packages (from faker) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\pooko\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-26.0.0-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
    --------------------------------------- 0.0/1.8 MB 640.0 kB/s eta 0:00:03
   - -------------------------------------- 0.1/1.8 MB 762.6 kB/s eta 0:00:03
   -- ------------------------------------- 0.1/1.8 MB 798.9 kB/s eta 0:00:03
   --- ------------------------------------ 0.2/1.8 MB 871.5 kB/s eta 0:00:02
   ------ --------------------------------- 0.3/1.8 MB 1.1 MB/s eta 0:00:02
   -------- ------------------------------- 0.4/1.8 MB 1.3 MB/s eta 0:00:02
   ---------- ----------------------------- 0.5/1.8 MB 1.4 MB/s eta 0:00:01
   ------------ --------------------------- 0.6/1.8 MB 1.5 MB/s eta 0:00:01
   --------------- ------------------------ 0.7/1.8 MB 1.6 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.8 MB 1.7 MB/s eta 0:00:01
   --------------------- ------------------ 1.0/1.8 MB 1.7 MB/s eta 0:00:01
   ---------------------- ----------------- 1.0/1.8 MB 1.7 MB/s eta 0:00:01
   ------------------------ --------------- 1.1/1.8 MB 1.7 MB/s eta 0:00:01
   --------------------------- ------------ 1.2/1.8 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 1.4/1.8 MB 1.8 MB/s eta 0:00:01
   -------------------------------- ------- 1.5/1.8 MB 1.8 MB/s eta 0:00:01
   ------------------------------------ --- 1.6/1.8 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 1.8/1.8 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 1.9 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-26.0.0

In [4]:
!pip install ace_tools

Collecting ace_tools
  Downloading ace_tools-0.0-py3-none-any.whl.metadata (300 bytes)
Downloading ace_tools-0.0-py3-none-any.whl (1.1 kB)
Installing collected packages: ace_tools
Successfully installed ace_tools-0.0

ModuleNotFoundError: No module named 'ace_tools'

In [17]:
from faker import Faker
import pandas as pd
import random
from datetime import timedelta

fake = Faker('ko_KR')

# Sample data parameters
num_purchase_data = 100
num_items = 10
num_users = 20
num_shipments = 50

# Generate unique IDs
user_ids = [fake.uuid4() for _ in range(num_users)]
shipment_ids = [fake.uuid4() for _ in range(num_shipments)]
items = [fake.word() for _ in range(num_items)]
# Define Korean item names
korean_items = ['사과', '바나나', '오렌지', '포도', '수박', '배', '딸기', '체리', '복숭아', '자두']

# Regenerate purchase data with Korean items
purchase_data_korean = []
for _ in range(num_purchase_data):
    purchase_date = fake.date()
    purchase_data_korean.append({
        '일자': purchase_date,
        '품목': random.choice(korean_items),
        '수량': random.randint(1, 1000),
        '구매자id': random.choice(user_ids),
        '운송장id': random.choice(shipment_ids)
    })

# Generate user data
user_data = []
for user_id in user_ids:
    user_data.append({
        '구매자id': user_id,
        '이름': fake.name(),
        '나이': random.randint(18, 70),
        '성별': random.choice(['남성', '여성']),
        '주소': fake.address()
    })

# Generate shipment data
shipment_data = []
for shipment_id in shipment_ids:
    shipment_date = fake.date()
    purchase_date = pd.to_datetime(shipment_date) - timedelta(days=random.randint(0, 14))
    shipment_data.append({
        '운송장id': shipment_id,
        '현재위치': fake.city(),
        '배송기사': fake.name(),
        '예상도착일자': purchase_date.strftime('%Y-%m-%d')
    })

# Convert to DataFrames
purchase_df = pd.DataFrame(purchase_data_korean)
user_df = pd.DataFrame(user_data)
shipment_df = pd.DataFrame(shipment_data)

# Save to CSV files
purchase_df.to_csv('./data/purchase_data_korean.csv', index=False, encoding='cp949')
user_df.to_csv('./data/user_data.csv', index=False, encoding='cp949')
shipment_df.to_csv('./data/shipment_data.csv', index=False, encoding='cp949')

In [11]:
purchase_df

,일자,품목,수량,구매자id,운송장id
0,1998-05-21,딸기,617,df022a15-da10-480a-90cc-bb7bb40fffed,45abc7cd-9d8d-4902-a3a4-d125bcbc92cc
1,1984-04-30,딸기,972,130cbf5f-94c5-4fbd-8123-879bf05e8ab4,2b07c9fe-0f7f-4608-8eff-c1916ce4cdf6
2,2014-11-18,사과,390,0a6f1401-ae1d-43c3-9a01-9dcbcb741f4e,86fdd197-ffe0-4c33-bcc8-6c47d36b1f71
3,2016-01-17,체리,168,d241c7d6-1ea3-49c7-b796-ca53b6eb5e4f,5f82d421-871a-43d9-aef0-60b29086dafd
4,1981-08-05,복숭아,559,2ddda257-fab8-4fa0-8187-19b8a20d8a8a,7011a841-2dc5-47c3-bc3b-f910449626f2
...,...,...,...,...,...
95,1984-07-07,체리,685,93fa9a70-69b4-4f00-9da1-f50c25000e31,3de068d6-e9ad-4e87-b323-142651aa7318
96,2000-01-08,오렌지,633,21d5e761-6e62-4e13-a09a-5334383a3578,58352b8c-610c-4044-b1b0-ee68446aab64
97,1999-01-08,배,160,130cbf5f-94c5-4fbd-8123-879bf05e8ab4,8095f7c7-412e-4d85-a16d-559fdba42b17
98,1984-02-03,복숭아,959,a899502c-2278-45a2-b129-a43533e493cb,5c0eef16-9ce2-4dc6-9b5c-9454201019d2
99,2023-05-19,바나나,679,d241c7d6-1ea3-49c7-b796-ca53b6eb5e4f,88c26ea0-784c-4d50-bc10-7540274d43c5

In [12]:
user_df

,구매자id,이름,나이,성별,주소
0,5d647bc1-9eff-4c92-898a-8b36b82f965e,황하윤,22,여성,전라남도 동해시 압구정로 (서준안김면)
1,45806b28-ef78-454d-b915-fa1e0404480c,강준서,51,여성,서울특별시 노원구 삼성05거리
2,df022a15-da10-480a-90cc-bb7bb40fffed,전미숙,18,남성,세종특별자치시 광진구 서초대길 (지우박면)
3,d241c7d6-1ea3-49c7-b796-ca53b6eb5e4f,김재현,56,여성,충청북도 오산시 강남대4거리 (상현박이동)
4,96c9517e-529d-49f5-a313-b2c68433e8eb,주시우,39,여성,부산광역시 강북구 역삼98길 (상훈김조마을)
5,e9370bc3-7e29-475e-a99f-b1ec1c624330,하상훈,63,여성,경기도 수원시 팔달구 역삼길
6,c6e0f70a-cb6c-46ed-80fe-3851a260d1b5,이서영,63,남성,대구광역시 강서구 테헤란거리
7,0a6f1401-ae1d-43c3-9a01-9dcbcb741f4e,윤경자,26,여성,전라북도 시흥시 역삼거리 (지민장읍)
8,21d5e761-6e62-4e13-a09a-5334383a3578,유서준,33,여성,충청북도 부천시 소사구 서초중앙길
9,3067c661-c901-48df-9279-4c869e8fc9c2,안수민,44,남성,세종특별자치시 중구 삼성0가 (성훈박강동)
10,93fa9a70-69b4-4f00-9da1-f50c25000e31,김영미,45,여성,경상북도 홍성군 압구정13거리
11,30d60676-ecd8-47ef-9be1-061a37301c6c,이정자,63,남성,제주특별자치도 금산군 선릉901가 (정희구리)
12,320c3ed4-5b45-4241-9dbd-4e3d9b21c0af,한민석,32,남성,경상북도 양주시 석촌호수3길 (영호오이읍)
13,cca4d687-8f02-4947-b88e-9f0492afe016,박성민,65,여성,울산광역시 성동구 백제고분9로
14,a6ffbb8d-ea84-45f3-bac5-c9bbb8056264,박현우,23,남성,강원도 의정부시 서초대994거리 (민준김동)
15,a899502c-2278-45a2-b129-a43533e493cb,송아름,44,남성,대전광역시 북구 삼성길
16,e3f69c67-81c1-4438-a366-54be64542e6e,황예원,68,여성,대전광역시 금천구 봉은사길
17,130cbf5f-94c5-4fbd-8123-879bf05e8ab4,이도현,20,남성,충청북도 보은군 삼성85로 (보람이읍)
18,2ddda257-fab8-4fa0-8187-19b8a20d8a8a,이옥순,63,여성,인천광역시 중랑구 영동대길
19,aef230c7-eb88-47f6-b821-f02bcc6d2048,백영길,18,여성,충청남도 청양군 압구정거리 (정웅박마을)

In [13]:
shipment_df

                                   운송장id      현재위치 배송기사      예상도착일자
0   907daf50-0e39-4cda-afbd-01a1e1312e00       보은군  이순옥  2013-07-27
1   68ea8a72-6f3c-40b7-acc1-3e35f34ad602       화천군  류진호  2021-06-28
2   3094fc76-877e-43da-a485-ebf56e7c5612       평택시  남성현  1975-09-19
3   7011a841-2dc5-47c3-bc3b-f910449626f2   천안시 서북구  김혜진  2019-12-16
4   2b07c9fe-0f7f-4608-8eff-c1916ce4cdf6       충주시  장지혜  2012-01-01
5   8b091b92-2e95-4be4-b333-f3fa5b6f1711   고양시 덕양구  박영희  2019-10-16
6   806966ff-3b93-4421-bb84-76f933f49b71   성남시 분당구  이수빈  1996-09-04
7   86fdd197-ffe0-4c33-bcc8-6c47d36b1f71   청주시 서원구  이도윤  2023-12-11
8   45abc7cd-9d8d-4902-a3a4-d125bcbc92cc       포천시  구상현  2017-04-17
9   30bd17cf-83ef-46bb-b437-5125e8fc3559   천안시 서북구  최옥순  2010-06-21
10  e6b194b9-8426-449a-b06d-3c48fbfc8880       옥천군  김수빈  1993-11-02
11  b947bbbc-a3ff-48c1-9c1c-e0d52708d333       태백시  하준호  1983-10-30
12  a412cb19-639d-4dbb-8131-0f96e564498f       화천군  박정자  2015-09-04
13  9ff8bd6e-53c8-4aae-af8c-4cb2cb0a4c03       보은군  심옥자  1993-06-13
14  ae8046c6-5c0f-4ed7-9b58-bfc55800a858   청주시 상당구  이은주  1978-10-17
15  88c26ea0-784c-4d50-bc10-7540274d43c5   용인시 처인구  이경자  2004-10-03
16  b8561251-7995-434b-aea1-500114ad8acb       홍성군  성재현  2008-08-28
17  5f82d421-871a-43d9-aef0-60b29086dafd       평창군  엄미영  1993-04-26
18  7c673d6a-7d17-420f-aefb-1ba2c5feab22   부천시 원미구  문영미  1996-03-21
19  8db250d4-e64d-4bba-aea5-463f636a48e4       강릉시  장우진  1986-09-05
20  315eedcd-85d5-49ac-bf66-155c081d2ad5       부천시  김예준  1997-07-15
21  d2274bf3-c22d-4454-b786-66bea619fd60   성남시 분당구  손은서  2001-04-08
22  777ec14d-26e6-4887-b6cb-53ab2344957f       홍천군  전준호  2021-11-18
23  befb9dbd-e1f1-4f7c-afff-370b4ac0ac5c       춘천시  김성민  1988-01-04
24  ff465f55-96ad-40d9-9983-7d3b8cb3c83f       제천시  김상현  1978-03-16
25  9429fe82-0a44-415c-b511-db51accd9afd   수원시 장안구  김서현  1996-12-29
26  331dcd29-8573-494d-a774-73a26e10fbd4       화성시  이건우  2022-02-13
27  edb3e712-c5a9-4ff9-b520-6eb52594bd67       구리시  황민수  1989-03-22
28  cdabe8af-bcc5-4f69-907d-7901f3104b06       양양군  장성훈  2017-05-05
29  0ee91700-031c-4fb8-9ce8-24abb9c44471  고양시 일산서구  김성진  1990-12-20
30  4d67f65f-996c-4c92-b0db-c63aa12c82bb       청양군  김성훈  1998-09-23
31  17d3c047-3dee-414a-84b6-7e479a89e705   수원시 팔달구  김서윤  1999-01-12
32  ab63068e-2a3f-4dba-a4a9-44036ddcf962       정선군  손지현  1986-08-21
33  c5d08689-bb9c-46ea-a118-e71cec3e8c27       안성시  장수빈  2007-06-26
34  3de068d6-e9ad-4e87-b323-142651aa7318   안산시 단원구  주미정  2011-11-14
35  15e46e9d-a40e-4ca2-aed9-c823e997e402       논산시  김명자  2002-10-24
36  f4ae9947-baf1-4592-a4b7-bd16b4e27a11       정선군  박진우  1975-07-02
37  a82056f6-7c80-40cb-88f9-64fc92832c48       정선군  김채원  1972-07-06
38  b7f57faa-05f1-4dd3-8fa9-63145cbeea28       태안군  김성진  1971-02-19
39  e90189d9-3a6f-4e61-aaf4-42e46d8b2ec9       단양군  이은영  2020-11-08
40  763eedc6-cb1d-4493-873c-62dcde71bff9       평창군  최혜진  2024-03-12
41  58352b8c-610c-4044-b1b0-ee68446aab64       태백시  김서영  1999-05-10
42  8095f7c7-412e-4d85-a16d-559fdba42b17   고양시 덕양구  이정순  2015-11-16
43  a6e742a4-3abb-466e-ac99-0b4a83e4d34f       괴산군  윤정호  1997-07-26
44  c085f492-fa73-46db-9515-fe386cb3f600   안양시 만안구  하예은  1998-12-07
45  5c0eef16-9ce2-4dc6-9b5c-9454201019d2       평택시  박진우  2003-05-18
46  f8c8c5b6-0f02-438c-bda2-bc86ad2f6ceb       시흥시  이지원  1994-08-12
47  e3a0c5a8-6f42-4fb8-9ab3-a0e8ad524cf8       인제군  박수진  1985-05-19
48  b00d40a7-895c-4fac-9748-b4c810be166e   청주시 서원구  안서영  1996-07-09
49  e161c86a-a925-44b1-ad55-9c3e709e835c   청주시 상당구  우정남  2004-03-02

In [19]:
# Adjusting the code to generate purchase dates within the last 2 years
from datetime import datetime

# Update sample data parameters
num_purchase_data = 100

# Regenerate purchase data with Korean items within the last 2 years
purchase_data_korean = []
for _ in range(num_purchase_data):
    purchase_date = fake.date_between(start_date='-2y', end_date='today')
    purchase_data_korean.append({
        '일자': purchase_date,
        '품목': random.choice(korean_items),
        '수량': random.randint(1, 1000),
        '구매자id': random.choice(user_ids),
        '운송장id': random.choice(shipment_ids)
    })

# Generate user data with 가입일자
user_data = []
for user_id in user_ids:
    user_data.append({
        '구매자id': user_id,
        '이름': fake.name(),
        '나이': random.randint(18, 70),
        '성별': random.choice(['남성', '여성']),
        '주소': fake.address(),
        '가입일자': fake.date_between(start_date='-5y', end_date='today')
    })

# Generate shipment data
shipment_data = []
for shipment_id in shipment_ids:
    purchase_date = fake.date_between(start_date='-2y', end_date='today')
    expected_delivery_date = pd.to_datetime(purchase_date) + timedelta(days=random.randint(0, 14))
    shipment_data.append({
        '운송장id': shipment_id,
        '현재위치': fake.city(),
        '배송기사': fake.name(),
        '예상도착일자': expected_delivery_date.strftime('%Y-%m-%d')
    })

# Convert to DataFrames
purchase_df = pd.DataFrame(purchase_data_korean)
user_df = pd.DataFrame(user_data)
shipment_df = pd.DataFrame(shipment_data)

# Save to CSV files
# Save to CSV files
purchase_df.to_csv('./data/purchase_data_korean.csv', index=False, encoding='cp949')
user_df.to_csv('./data/user_data.csv', index=False, encoding='cp949')
shipment_df.to_csv('./data/shipment_data.csv', index=False, encoding='cp949')